---
kind: pipeline
name: testing

steps:
- name: unittests
  image: 'golang:1.18'
  commands:
  # enable go modules
  - export GO111MODULE=on
  - mkdir -p report
  # run tests
  - go test -covermode=count -coverprofile=report/cover.out ./...

- name: lint
  image: 'golang:1.18'
  commands:
  - go get -u golang.org/x/lint/golint
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - golint -set_exit_status ./...

- name: staticcheck
  image: 'golang:1.18'
  depends_on:
  - lint
  commands:
  - go get -u honnef.co/go/tools/cmd/staticcheck
  # enable go modules
  - export GO111MODULE=on
  # run tests
  - staticcheck ./...
